Shader component almost finished
All the code is there however when trying to compile, it spits out
undefined reference to the functions from the shader component.
Also i need to think of a better thing to call this shader 'component'.